{"errorMessage":"Lambda process returned error status code: 1. Result: . Output:\nException in thread \"main\" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String (\"\") to element of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` (but could if coercion was enabled using `CoercionConfig`)\n at [Source: (String)\"\"\"\"; line: 1, column: 1]\n\tat com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)\n\tat com.fasterxml.jackson.databind.DeserializationContext.reportBadCoercion(DeserializationContext.java:1666)\n\tat com.fasterxml.jackson.databind.deser.std.StdDeserializer._checkCoercionFail(StdDeserializer.java:1445)\n\tat com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmptyString(StdDeserializer.java:325)\n\tat com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:270)\n\tat com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:444)\n\tat com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)\n\tat com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)\n\tat com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)\n\tat com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1491)\n\tat cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:60)","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1389, in _execute\n    process.run()\n","  File \"/usr/local/lib/python3.8/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1376, in do_execute\n    result = lambda_function_callable(inv_context.event, context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 912, in execute\n    result = lambda_executors.EXECUTOR_LOCAL.execute_java_lambda(\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1481, in execute_java_lambda\n    invocation_result = self._execute_in_custom_runtime(cmd, lambda_function=lambda_function)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1324, in _execute_in_custom_runtime\n    raise InvocationException(\n"]}
